language: php

sudo: false

php:
  - 5.6
  - 7.0

env:
  - CAKEPHP_VERSION="3.1.0"
  - CAKEPHP_VERSION="3.1.1"
  - CAKEPHP_VERSION="3.1.2"

install:
  - composer require cakephp/cakephp ${CAKEPHP_VERSION}

before_script:
  - cp config/app.default.php config/app.php
